version: '3.7'

services:
  nodejs:
    container_name: crud_app_nodejs
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: ./docker/NodeDockerfile.yml
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - .:/usr/src/app
    networks:
      - app
    depends_on:
      - mysql

  mysql:
      image: mysql:5.7
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DB}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
          - mysql:/var/lib/mysql
      ports:
          - ${MYSQL_PORT}
      networks:
          - app

networks:
  app:
    driver: bridge

volumes:
    mysql: